<?php

namespace Test\AbraFlexi\ui\TWB5;

use AbraFlexi\ui\TWB5\DocumentLink;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-06-26 at 09:26:10.
 */
class DocumentLinkTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var DocumentLink
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new DocumentLink();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    public function testLinkIsGeneratedCorrectly()
    {
        $mockEngine = $this->createMock(\AbraFlexi\Document::class);
        $mockEngine->expects($this->once())
            ->method('setMyKey')
            ->with('123');
        $mockEngine->expects($this->once())
            ->method('getApiUrl')
            ->with('pdf')
            ->willReturn('https://example.com/doc/123.pdf');
        $mockEngine->expects($this->once())
            ->method('getRecordIdent')
            ->willReturn('INV-123');

        $link = new DocumentLink($mockEngine, '123', 'pdf');
        $reflection = new \ReflectionClass($link);
        $hrefProperty = $reflection->getParentClass()->getProperty('href');
        $hrefProperty->setAccessible(true);
        $href = $hrefProperty->getValue($link);
        $this->assertEquals('https://example.com/doc/123.pdf', $href);
    }
}
