<?php

namespace Test\AbraFlexi\ui\TWB5;

use AbraFlexi\ui\TWB5\EmbedResponsiveHTML;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-06-26 at 09:26:11.
 */
class EmbedResponsiveHTMLTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var EmbedResponsiveHTML
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new EmbedResponsiveHTML();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    public function testIframeHtmlIsGeneratedCorrectly()
    {
        $mockSource = $this->createMock(\AbraFlexi\RO::class);
        $mockSource->expects($this->once())
            ->method('getEvidence')
            ->willReturn('invoice');
        $mockSource->expects($this->once())
            ->method('getMyKey')
            ->willReturn('123');

        $embed = new EmbedResponsiveHTML($mockSource, 'customfeeder.php');
        $reflection = new \ReflectionClass($embed);
        $contentProperty = $reflection->getParentClass()->getProperty('content');
        $contentProperty->setAccessible(true);
        $content = $contentProperty->getValue($embed);
        $this->assertStringContainsString('<iframe', $content);
        $this->assertStringContainsString('customfeeder.php?evidence=invoice&id=123&embed=true', $content);
    }

    public function testDefaultFeederIsUsed()
    {
        $mockSource = $this->createMock(\AbraFlexi\RO::class);
        $mockSource->expects($this->once())
            ->method('getEvidence')
            ->willReturn('invoice');
        $mockSource->expects($this->once())
            ->method('getMyKey')
            ->willReturn('456');

        $embed = new EmbedResponsiveHTML($mockSource);
        $reflection = new \ReflectionClass($embed);
        $contentProperty = $reflection->getParentClass()->getProperty('content');
        $contentProperty->setAccessible(true);
        $content = $contentProperty->getValue($embed);
        $this->assertStringContainsString('gethtml.php?evidence=invoice&id=456&embed=true', $content);
    }
}
