<?php

namespace Test\AbraFlexi\ui\TWB5;

use AbraFlexi\ui\TWB5\EmbedResponsive;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-06-26 at 09:26:10.
 */
class EmbedResponsiveTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var EmbedResponsive
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new EmbedResponsive();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers AbraFlexi\\ui\\TWB5\\EmbedResponsive::finalize
     */
    public function testfinalize() {
        $embed = new EmbedResponsive();
        $embed->finalize();
        $reflection = new \ReflectionClass($embed);
        $cssProperty = $reflection->getParentClass()->getProperty('css');
        $cssProperty->setAccessible(true);
        $css = $cssProperty->getValue($embed);
        $this->assertStringContainsString('.embed-responsive', $css);
    }

    public function testFinalizeAddsCss()
    {
        $embed = new EmbedResponsive();
        $reflection = new \ReflectionClass($embed);
        $cssProperty = null;
        // Try to get the css property from parent or grandparent
        $parent = $reflection->getParentClass();
        while ($parent && !$cssProperty) {
            if ($parent->hasProperty('css')) {
                $cssProperty = $parent->getProperty('css');
                $cssProperty->setAccessible(true);
                break;
            }
            $parent = $parent->getParentClass();
        }
        $this->assertNotNull($cssProperty, 'CSS property not found in parent classes');
        $this->assertEmpty($cssProperty->getValue($embed));
        $embed->finalize();
        $css = $cssProperty->getValue($embed);
        $this->assertIsString($css);
        $this->assertNotEmpty($css);
        $this->assertStringContainsString('.embed-responsive', $css);
    }
}
